# Generated by Django 2.2.1 on 2020-01-22 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeloactivo',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modeloactivo_creado_por', to=settings.AUTH_USER_MODEL),
        ),
    ]
