# Generated by Django 2.2.1 on 2020-01-09 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('modeloactivo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administracion.ModeloActivo')),
                ('nombre', models.CharField(max_length=300)),
                ('nacimiento', models.DateField()),
                ('ciudad', models.CharField(max_length=300)),
            ],
            bases=('administracion.modeloactivo',),
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('modeloactivo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administracion.ModeloActivo')),
                ('nombre', models.CharField(max_length=300)),
                ('fecha_creacion', models.DateField()),
                ('ciudad', models.CharField(max_length=300)),
            ],
            bases=('administracion.modeloactivo',),
        ),
        migrations.CreateModel(
            name='Tematica',
            fields=[
                ('modeloactivo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administracion.ModeloActivo')),
                ('nombre', models.CharField(max_length=300)),
            ],
            bases=('administracion.modeloactivo',),
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('modeloactivo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administracion.ModeloActivo')),
                ('titulo', models.CharField(max_length=300)),
                ('autor_libro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.Autor')),
                ('editorial_libro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.Editorial')),
            ],
            bases=('administracion.modeloactivo',),
        ),
    ]
