# Generated by Django 2.2.1 on 2020-01-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='temas',
            field=models.ManyToManyField(to='catalogo.Tematica'),
        ),
    ]
